# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-23 17:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
            ],
        ),
        migrations.CreateModel(
            name='Excursions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('main_text', models.CharField(max_length=100, verbose_name='\u0410\u043d\u043e\u043d\u0441 \u0434\u043b\u044f \u0441\u043f\u0438\u0441\u043a\u0430')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u0421\u043e\u0434\u0435\u0440\u0436\u0430\u043d\u0438\u0435')),
                ('list_image', models.ImageField(upload_to='./img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0432 \u0441\u043f\u0438\u0441\u043e\u043a')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('main', models.BooleanField(default=False, verbose_name='\u041d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e')),
                ('slide_image', models.ImageField(blank=True, upload_to='./img', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u0443\u044e')),
                ('slide_cropping', image_cropping.fields.ImageRatioField('slide_image', '650x430', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='slide cropping')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='./img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Excursions')),
            ],
        ),
    ]
