# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='./img', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('slide_cropping', image_cropping.fields.ImageRatioField('images', '380x240', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='slide cropping')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Gallery')),
            ],
        ),
        migrations.AddField(
            model_name='excursions',
            name='slide',
            field=models.BooleanField(default=False, verbose_name='\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0444\u043e\u0442\u043e\u0430\u043b\u044c\u0431\u043e\u043c'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('list_image', '500x300', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
