# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160624_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursions',
            name='main_text',
            field=models.CharField(max_length=160, verbose_name='\u0410\u043d\u043e\u043d\u0441 \u0434\u043b\u044f \u0441\u043f\u0438\u0441\u043a\u0430'),
        ),
    ]
